"""create new table

Revision ID: 14315d41bbc3
Revises: 386d436a0437
Create Date: 2026-05-15 16:53:00.316152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14315d41bbc3'
down_revision: Union[str, Sequence[str], None] = '386d436a0437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkin', sa.Column('xp_earned', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('streak', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET streak = 0 WHERE streak IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'streak')
    op.drop_column('checkin', 'xp_earned')
    # ### end Alembic commands ###
