"""create table

Revision ID: 386d436a0437
Revises: 
Create Date: 2026-05-12 23:40:25.889221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '386d436a0437'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('xp', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('dream',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('specific_items', sa.JSON(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('checkin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('dream_id', sa.Integer(), nullable=False),
                    sa.Column('hours', sa.Float(), nullable=False),
                    sa.Column(
                        'note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_day', sa.Date(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['dream_id'], ['dream.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    op.drop_table('dream')
    op.drop_table('user')
    # ### end Alembic commands ###
