"""add new field in user model

Revision ID: cbb2fc462b64
Revises: 14315d41bbc3
Create Date: 2026-05-24 23:21:31.318610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbb2fc462b64'
down_revision: Union[str, Sequence[str], None] = '14315d41bbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkin', 'xp_earned',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.add_column('user', sa.Column(
        'last_checkin_date', sa.Date(), nullable=True))
    op.alter_column('user', 'streak',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'streak',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('user', 'last_checkin_date')
    op.alter_column('checkin', 'xp_earned',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    # ### end Alembic commands ###
