"""add new table Path and PathPurchase

Revision ID: eba9ec74d035
Revises: cbb2fc462b64
Create Date: 2026-05-30 20:26:15.449020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eba9ec74d035'
down_revision: Union[str, Sequence[str], None] = 'cbb2fc462b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pathpurchase',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('path_id', sa.Integer(), nullable=False),
                    sa.Column('purchased_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['path_id'], ['path.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('checkin', 'xp_earned',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('user', 'streak',
                    existing_type=sa.INTEGER(),
                    nullable=True)

    # ### end Alembic commands ###


op.execute("UPDATE checkin SET xp_earned = 0 WHERE xp_earned is NULL")
op.execute("UPDATE \"user\" SET streak = 0 WHERE streak is NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'streak',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('checkin', 'xp_earned',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.drop_table('pathpurchase')
    op.drop_table('path')
    # ### end Alembic commands ###
